#Cadastro das informações...
print("Digite o nome da Empresa:")
MyCompany = (input())
print("Digite o nome do gestor:")
MyManager = (input())
print("Digite o seu cargo atual:")
MyJob = (input())
print("Digite a data de início do aviso prévio:")
StartDate = (input())
print("Digite a data de término do aviso prévio:")
EndDate = (input())
print("Digite local:")
Location = (input())
print("Digite a data de hoje:")
CurrentDate = (input())
print("Digite seu nome completo:")
FullName = (input())

#Impressão da Carta de Demissão...
print(f"À {MyCompany},")
print(f"Prezado(a) {MyManager},")
print(f"Venho por meio desta carta comunicar formalmente o meu pedido de demissão do cargo de {MyJob}.")
print(f"Estarei à disposição da empresa durante o aviso prévio, no período de {StartDate} a {EndDate}.")
print(f"Local e Data: {Location} {CurrentDate}")
print("Assinatura:")
print(f"Nome Completo:{FullName}")
